name: new_artist_project
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  firebase_messaging: ^6.0.13
#  image_picker: 0.4.12+1
  bottom_navy_bar: ^3.0.0
  carousel_slider: ^1.3.0
  page_indicator: ^0.3.0
#  camera: 0.4.2
  fancy_bottom_navigation: ^0.3.2
#  video_player: ^0.10.8+1

  neeko: ^0.0.6
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
#  flutter_tags: "^0.1.9"
  logging: ^0.11.3+2
  dio: ^3.0.8
  json_annotation: ^3.0.0
  flutter_staggered_grid_view: ^0.3.0
  sailor: ^0.4.0
  provider: ^3.1.0
  rxdart: ^0.22.2
  validators: ^2.0.0+1
  flutter_spinkit: ^3.1.0
  image_picker: ^0.6.3+1
  multi_media_picker: ^0.2.3
#  sqflite: ^1.1.6+3

  shared_preferences: ^0.5.4+10
  kiwi: ^0.2.0
  flutter_html: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.6.8
  mockito: ^4.1.0
  json_serializable: ^3.2.3
  build_runner: ^1.6.7
  pedantic: ^1.8.0+1
  async: ^2.3.0
  kiwi_generator: ^0.4.0
#  flutter_tags: "^0.1.9"
  font_awesome_flutter: ^8.5.0
  url_launcher: ^5.4.1
dependency_overrides:
  test_api: ^0.2.11
  analyzer: ^0.39.4



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
    #  - family: Trajan Pro
    #    fonts:
    #      - asset: fonts/TrajanPro.ttf
    #      - asset: fonts/TrajanPro_Bold.ttf
    #        weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
